version: '3.9'

services:
  django-app:
    build:
      context: .
      target: dev
    ports:
      - '8000:8000'
    command: 'python manage.py runserver 0.0.0.0:8000'
    environment:
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - DJANGO_SECRET
      - DJANGO_SUPERUSER_PASSWORD
      - DJANGO_SUPERUSER_EMAIL
      - DJANGO_SUPERUSER_USERNAME
      - DJANGO_SETTINGS_MODULE=store.settings.dev
    depends_on:
      db:
        condition: service_healthy
    # links:
    #   - db
    volumes:
      - ./app:/app

  db:
    image: postgres:15
    ports:
      - '5432:5432'
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 10
# volumes:
#   database:
